### ISSUE TITLE
Worlds tracker > Unable to delete Patrons Known & Rivals Known

### ISSUE THREAD

**Issue by dmpunks** [sheibeck/fiveparsecscompanion#17]
Please add a way to delete Patrons Known and also Rivals Known. Thanks!

**Comment by sheibeck** [comment]
Woah! I can't believe I missed this functionality. Thanks for reporting it. I've pushed a fix to production. Happy gaming!

**Comment by dmpunks** [comment]
Thanks! Works like a charm!
