### ISSUE TITLE
Printed/PDF crew logs do not print crew members' background, motivation and class

### ISSUE THREAD

**Issue by dmpunks** [sheibeck/fiveparsecscompanion#20]
As the title says: the PDF only prints each crew member's Species field. Background, Motivation and Class are not printed.

**Comment by sheibeck** [comment]
I actually took this off on purpose because when I added them in, I wasn't able to print a full 6 members on one sheet. I'll look at adding them back in.

**Comment by sheibeck** [comment]
This is now fixed. Thanks for the input.
