### ISSUE TITLE
Crew Log > Cannot save when Stash contains item that starts with a number

### ISSUE THREAD

**Issue by nanux** [sheibeck/fiveparsecscompanion#32]
**Reproduction steps**
1. Open Crew Log
2. Enter `3 Fuel` to `Stash`
3. Save

**Expected**
It saves the crew

**Actual**
Nothing happens

**Comment by sheibeck** [comment]
Thanks for reporting this! I found the issue and will be fixed in the next release. I'm testing a rework of the battle page, so might be a few days yet.

**Comment by sheibeck** [comment]
This is now fixed.
