### ISSUE TITLE
Weapon ranges and other statistics

### ISSUE THREAD

**Issue by nanux** [sheibeck/fiveparsecscompanion#33]
Currently, it is necessary to fill in all the weapon details when creating crew and in the Encounter sheet.

I wonder if it is on purpose or just wasn't implemented due to time constraints?

General question: @sheibeck, would you be open to accepting PRs? I started looking on the code today and even though I am not an expert frontender I might give the weapons a shot (no pun intended).

I tried to start the development instance locally but even when I opened a trial AWS account to create Amplify service and created Google consent dialogue in their API, I still wasn't able to log in and use the application. Is there any simpler way how to start without AWS and Google dependencies?

**Comment by sheibeck** [comment]
I didn't fill those out only for sake of time. I was hoping to get around to it eventually. I threw this thing together so the code is a train wreck. I "think" you should be able to operate without using any of the AWS dependencies. 

I'm totally open to a PR if you're willing. The readme isn't right at all for the project though. You should only have to run **yarn install**. Then run  **yarn serve** and it should run locally for you without needing any connections to AWS (It'll just use your local datastore instead of the AWS db). This will spin you up on localhost:8080, which should have all the permission for logging in via your existing gmail account. 

In theory anyway.

**Comment by nanux** [comment]
Unfortunately I wasn't successful and cannot login to local instance. I
believe it tries to use the staging backend that doesn't contain my user.
Is there any way how to use some test user? It would be great if I can get
local development going but I don't want to put strain on you as I am sure
this is a hobby project. If it is complicated I can spend a bit more time
to try to figure it out.

**Comment by sheibeck** [comment]
You can turn off the datasync by doing this:

> The approach is slightly different. Look for any API configurations in the aws-exports.js file, and remove them. Specifically, you should remove any config entries with aws_appsync_* in the prefix:
> 
> const awsmobile = {
>     // ...
>     "aws_appsync_graphqlEndpoint": "https://yourid.appsync-api.us-east-1.amazonaws.com/graphql",
>     "aws_appsync_region": "us-east-1",
>     "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
>     // ...
> };

Let's try this to get you up and running on the staging login:
Navigate to the beta site https://develop.d1tp5cd86hfjxz.amplifyapp.com/. You should get a popup window asking you to authenticate to the site:
u: 5pfh
p: fiveparsecs

Once that lets you in, try logging in there.
Question though, are you using your Gmail to login via clicking the AWS button and then using the single sign-on option?
Gmail option should work on the beta site which then should let your local instance work after you setup your user there.

We'll see how it goes. I'm using several different gmail accounts to login, so there's nothing specific about my user really. Let's see if this gets you up and running. Thanks for being willing to work though this.

**Comment by sheibeck** [comment]
FYI, I just updated the **Develop** branch to support Weapon/Enemy stats. In the **tablesBattle.js** file, I put placeholders for all of the data. Even if you can't actually run the app, if you have some time to fill out the data from the book into that branch/file, even that would be tremendously helpful. Just wanted to set something up to allow you to partake if you're willing. Just not sure when I can get around to putting all the data in. Cheers!

**Comment by nanux** [comment]
Thank you! I will give it a go later this week.

**Comment by nanux** [comment]
I can see you've added the weapon stats already. I am still struggling to get the project running locally as the existing `staging` doesn't pull locally and mock server doesn't start as well. For now, I am not going to focus on getting it going but rather helping with data input.

I should be able to create a PR for the enemies today.

**Comment by sheibeck** [comment]
Thank you so much!

I'll do some more research to see if I can figure out how to get you up and
running.

**Comment by nanux** [comment]
Enemies stats https://github.com/sheibeck/fiveparsecscompanion/pull/40

**Comment by sheibeck** [comment]
Awesome, thank you. I see you removed the google auth. Did that help you get up and running at all? Most of that stuff was auto-setup when I spun up the project using AWS Amplify. So, it's a little bit of a black box to me still.

**Comment by nanux** [comment]
I am closing the issue as the weapon ranges were added and deployed. Thank you!
