### ISSUE TITLE
Suggestion: Crew printing order

### ISSUE THREAD

**Issue by dabolter** [sheibeck/fiveparsecscompanion#46]
Hi
I am mainly using this as a way of recording my crew roster, patrons, rivals and world notes. It works excellently for this, but now my crew is larger than 6. I have a Robot in the repair shop and I have a KIA. Is there a way of changing the order of the crew in the printout, so I can get the relevant people on one page ?
At the moment the only way I can think of is to delete a crew member and add them in again at the bottom.

**Comment by sheibeck** [comment]
Thanks for the suggestion! This has been added in version 1.0.2. You'll see checkboxes near the print button that will allow you to hide KIA and Sickbay crew. By default, these will be checked, and so will be hidden on print unless you explicitly uncheck them.

https://github.com/sheibeck/fiveparsecscompanion/releases/tag/1.0.2
