### ISSUE TITLE
Please allow adding line breaks in inventory stash

### ISSUE THREAD

**Issue by pugamer1** [sheibeck/fiveparsecscompanion#55]
It would be nice to be able to add line breaks in the equipment stash area to make it easier to scan through the list of items.  Right now everything is added in paragraph form, even if line breaks are added during text entry.

The following is a screenshot of the text during entry:
![image](https://github.com/sheibeck/fiveparsecscompanion/assets/3626474/7c2be8ba-06ed-4e9b-a26f-da4f23ba7060)

The following is the resulting text after saving the crew:
![image](https://github.com/sheibeck/fiveparsecscompanion/assets/3626474/f5ddbc84-f27c-40fe-a2d3-0261bfee8633)

**Comment by pugamer1** [comment]
Also, it looks like when I go back into editing the stash, the line breaks are there.  It's more like they're not being displayed vs not being retained.

**Comment by sheibeck** [comment]
Thanks for the request. I'll see what I can do!
