### ISSUE TITLE
Print option to only display active crew information

### ISSUE THREAD

**Issue by pugamer1** [sheibeck/fiveparsecscompanion#56]
Not so much a bug or issue, but it would be very helpful to a printable crew sheet to reference while playing.  At first thought just removing the crew summary, stash, and ship sections at the top, as well as the planet sections at the bottom would probably do it.  For crews with more than six members or missions that don't include all crew members, being able to select which are included in the printout would also be nice.

It's nice to have them all together as well, but for the tabletop having just the crew info would allow it to print on a single page.  (With all sections it spans multiple pages and they don't break cleanly.)

Thanks!!

**Comment by sheibeck** [comment]
Could you provide me with what your print looks like? You should be able to print your crew all on one page if you specify landscape mode and reduce you margins to the minimum possible. There's a print button located next to the Edit Crew Log button, that should take care of removing elements from the UI and give you a clean print that breaks cleanly.

**Comment by pugamer1** [comment]
Sure thing!  I recognize this is a screen cap from my phone, but I'm using the desktop site.  I'm thinking it might be due to the large amount of items in my stash?

![Screenshot_20230911-200445](https://github.com/sheibeck/fiveparsecscompanion/assets/3626474/ccfed63a-7409-48e3-a34c-eb096c65754e)
![Screenshot_20230911-200425](https://github.com/sheibeck/fiveparsecscompanion/assets/3626474/984473de-b884-4ee2-89e0-3f5f12049881)

I've included both portrait and landscape views as well.  Tha ks so much for looking into this!!

**Comment by pugamer1** [comment]
The planet listing breaks cleanly on a third page.  My initial thought was to have the upper section break similarly between the top section and the crew section.

**Comment by sheibeck** [comment]
Ahh, I see now. Your stash is big enough that it's pushing things down the sheet. There's definitely a lot of data being squeezed in here and that makes it hard.  I'll see what I can do.

**Comment by sheibeck** [comment]
I pushed up some changes, let me know if they help things for you.

**Comment by pugamer1** [comment]
Looks great!  Not a big deal, but the formatting when printing from the mobile site is still off a bit, but it works great when viewed in desktop mode:

![Screenshot_20230912-141036](https://github.com/sheibeck/fiveparsecscompanion/assets/3626474/985d83d8-12cd-4ef4-b94e-e4de724b3aa3)
![Screenshot_20230912-141008](https://github.com/sheibeck/fiveparsecscompanion/assets/3626474/e738167c-ba6d-420f-af82-1bab17dd12e0)
